### ISSUE TITLE
Error with galaxy poppunk tool. 

### ISSUE THREAD

**Issue by JayanthiGangiredla** [johnlees/PopPUNK_galaxy#1]
Dataset Error Report
An error occurred while running the tool toolshed.g2.bx.psu.edu/repos/johnlees/poppunk/poppunk_cluster/1.1.6.

Details
Execution resulted in the following messages:

Fatal error: Exit code 1 ()
Tool generated the following standard error:

Traceback (most recent call last):
  File "/dep/_conda/envs/__poppunk@1.1.6/bin/poppunk", line 6, in <module>
    from PopPUNK.__main__ import main
  File "/dep/_conda/envs/__poppunk@1.1.6/lib/python3.9/site-packages/PopPUNK/__main__.py", line 16, in <module>
    from .mash import checkMashVersion
  File "/dep/_conda/envs/__poppunk@1.1.6/lib/python3.9/site-packages/PopPUNK/mash.py", line 24, in <module>
    from .plot import plot_fit
  File "/dep/_conda/envs/__poppunk@1.1.6/lib/python3.9/site-packages/PopPUNK/plot.py", line 20, in <module>
    from sklearn.neighbors.kde import KernelDensity
ModuleNotFoundError: No module named 'sklearn.neighbors.kde'

**Comment by johnlees** [comment]
Thanks for reporting this. When sklearn moved from 0.24 to 1.0 they moved `sklearn.neighbours.kde` to `sklearn.neighbors.KernelDensity`. I think to stick with poppunk v1.1.6 you'd need to make sure sklearn is no higher than v0.24 when importing.

Do you know how to specify imports with galaxy? I can see [all I have is](https://github.com/johnlees/PopPUNK_galaxy/blob/master/tools/PopPUNK/poppunk_cluster.xml#L4-L6)
```
   <requirements>
        <requirement type="package" version="1.1.6">poppunk</requirement>
     </requirements>
```
Which means pip will try and import the latest versions of all the requirements.
Could we just add:
```
<requirement type="package" version="0.24">sklearn</requirement>
```

We actually only support poppunk v2 and higher now, and at some point in the near future I will write an updated wrapper to use this new version.
